version: '3.7'

services:

  traduora:
    image: everco/ever-traduora:latest
    ports:
     - "172.17.0.1:9090:8080"
    environment:
      TR_DB_USER: tr
      TR_DB_PASSWORD: change_me
      TR_DB_DATABASE: tr_dev
      TR_DB_HOST: mysqldb
      TR_DB_PORT: 3306
      NODE_ENV: "production"
      TR_SECRET: ${TR_SECRET}    
      TR_VIRTUAL_HOST: ${TR_VIRTUAL_HOST}
      TR_MAIL_SENDER: ${TR_MAIL_SENDER}
      TR_MAIL_HOST: ${TR_MAIL_HOST}
      TR_MAIL_PORT: ${TR_MAIL_PORT}
      TR_MAIL_SECURE: ${TR_MAIL_SECURE}
      TR_MAIL_REJECT_SELF_SIGNED: ${TR_MAIL_REJECT_SELF_SIGNED}
      TR_MAIL_USER: ${TR_MAIL_USER}
      TR_MAIL_PASSWORD: ${TR_MAIL_PASSWORD}
    restart: always
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: tr_dev
      MYSQL_USER: tr
      MYSQL_PASSWORD: change_me
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'